name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    ci-linux:
        name: Linux ${{ matrix.recipe }}
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/tara-zero/tokio-immediate-ci-base:main-2026-02-16

        strategy:
            fail-fast: false
            matrix:
                recipe:
                    - fmt-check
                    - clippy
                    - build
                    - test
                    - doc

        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Run CI recipe
              env:
                  # GitHub Linux runners replace image's HOME with some nonsense that messes up
                  # with our container setup.
                  HOME: /root
              run: just ${{ matrix.recipe }}

    ci-macos:
        name: macOS ${{ matrix.recipe }}
        runs-on: macos-latest

        strategy:
            fail-fast: false
            matrix:
                recipe:
                    - clippy
                    - build
                    - test

        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Install Rust toolchain
              uses: dtolnay/rust-toolchain@stable
              with:
                  # Must be in sync with `$SRC_ROOT/rust-toolchain.toml`.
                  # Must be in sync with `$SRC_ROOT/ci/container/base/Containerfile`.
                  toolchain: 1.93.1
                  components: clippy

            - name: Install just
              uses: taiki-e/install-action@just

            - name: Run CI recipe
              run: just ${{ matrix.recipe }}

    ci-windows:
        name: Windows ${{ matrix.recipe }}
        runs-on: windows-latest

        strategy:
            fail-fast: false
            matrix:
                recipe:
                    - clippy
                    - build
                    - test

        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Install Rust toolchain
              uses: dtolnay/rust-toolchain@stable
              with:
                  # Must be in sync with `$SRC_ROOT/rust-toolchain.toml`.
                  # Must be in sync with `$SRC_ROOT/ci/container/base/Containerfile`.
                  toolchain: 1.93.1
                  components: clippy,rust-analyzer,rust-src

            - name: Install just
              uses: taiki-e/install-action@just

            - name: Install LLVM/Clang
              uses: KyleMayes/install-llvm-action@v2
              with:
                  version: "20"

            - name: Run CI recipe
              run: just ${{ matrix.recipe }}
